version: '3'

services:
  back:
    build: .
    container_name: bk01
    env_file:
      - .env
    command: >
      bash -c "sh /back/script/ngs_read_service.sh start && sh /back/script/ngs_write_service.sh start"
    volumes:
      - .:/back
      - ${LOG_PATH}:/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8086:8086"
      - "8088:8088"
    networks:
      - backend

networks:
  backend:
      ipam:
        config:
          - subnet: 172.28.0.0/16

