version: "3"
services:
    web:
        image: nginx:latest
        container_name: fr01
        ports:
            - 88:80
        volumes:
            - ./html:/usr/share/nginx/html
        networks:
            - frontend

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.27.0.0/16